Repository semigroups/Semigroups, pull requests merged in 2018-06, with the labels that each got.

#487 grpperm: improve default IsomorphismPermGroup
  gap/semigroups/grpperm.gi
  tst/standard/grpperm.tst
Labels: 3.0, improvement

#495 Fix tests for GAP master
  gap/tools/utils.gi
  tst/standard/attr.tst
  tst/standard/normalizer.tst
  tst/standard/semigrp.tst
  tst/testinstall.tst
Labels: 3.0, 3.1, minor

#499 kernel: update to check for GAP kernel version for GVarFilt definition
  src/pkg.cc
Labels: 3.0, 3.1, bug, minor

#498 Fix issue 496
  src/bipart.cc
Labels: 3.0, bug
