Repository semigroups/Semigroups, pull requests merged in 2018-09, with the labels that each got.

#514 Release candidate for v3.0.18
  CHANGELOG.md
  PackageInfo.g
  VERSION
  VERSIONS
Labels: 3.0, release-candidate

#516 Update Travis setup
  .travis.yml
  scripts/travis-test.sh
Labels: minor, travis

#520 Require IsSemigroup in the filters for the IsCommutative TrueMethod
  gap/attributes/properties.gd
Labels: bug, minor

#525 Update some testing details and create teststandard.g
  PackageInfo.g
  gap/tools/utils.gi
  tst/teststandard.g
Labels: 3.*, improvement

#539 ideals: resolve Issue 530 (IsFactorisableInverseMonoid)
  gap/ideals/ideals.gi
  tst/standard/ideals.tst
Labels: 3.*, bug

#540 freeinverse: use non-impl. dep. free group iterator
  gap/fp/freeinverse.gi
Labels: 3.*, bug-fix

#541 PackageInfo: don't use Info in TestAvail.*
  PackageInfo.g
Labels: 3.*, bug-fix

#544 Adjust for compatibility with all packages loaded
  gap/attributes/properties.gi
  tst/standard/freeinverse.tst
  tst/standard/properties.tst
Labels: 3.*

#546 Bump libsemigroups version to v0.6.4
  .LIBSEMIGROUPS_VERSION
Labels: 3.*, libsemigroups
