Repository semigroups/Semigroups, pull requests merged in 2018-11, with the labels that each got.

#558 Rename 'IsDecomposableSemigroup' to 'IsSurjectiveSemigroup'
  doc/attr.xml
  doc/properties.xml
  doc/z-chap15.xml
  gap/attributes/attr.gi
  gap/attributes/attrfp.gi
  gap/attributes/properties.gd
  gap/attributes/properties.gi
  gap/semigroups/semidp.gi
  tst/standard/attr.tst
  tst/standard/attrfp.tst
  tst/standard/properties.tst
Labels: 3.*

#507 Make McAlister triple semigroups acting
  doc/semieunit.xml
  gap/main/setup.gi
  gap/semigroups/semieunit.gd
  gap/semigroups/semieunit.gi
  tst/standard/semieunit.tst
  tst/standard/setup.tst
Labels: 4.*, improvement, major

#564 Stop testing IsInverseSemigroup when making a direct product
  gap/semigroups/semidp.gi
  tst/standard/semidp.tst
Labels: critical

#565 Fix GeneratorsOfSemigroup immediate method for partial perm groups
  gap/semigroups/semipperm.gi
  tst/standard/semipperm.tst
Labels: bug

#535 Improve methods for multiplicative zeroes
  gap/attributes/attr.gi
  gap/elements/elements.gi
  gap/ideals/ideals.gi
  tst/standard/elements.tst
  tst/standard/ideals.tst
Labels: 3.*, performance

#567 The empty semigroup is not monogenic
  gap/attributes/properties.gi
  tst/standard/properties.tst
Labels: bug-fix

#569 Add pickling of Rees (0-)matrix semigroups
  gap/semigroups/semirms.gi
  gap/tools/io.gi
  tst/standard/semirms.tst
Labels: 3.*, new-feature

#568 semigroups: operator \<
  gap/semigroups/semibipart.gi
  gap/semigroups/semigrp.gi
  gap/semigroups/semipbr.gi
  gap/semigroups/semipperm.gi
  gap/semigroups/semitrans.gi
  tst/standard/semibipart.tst
  tst/standard/semipbr.tst
  tst/standard/semipperm.tst
Labels: new-feature

#570 Clean comments
  gap/congruences/congsimple.gd
  gap/semigroups/semidp.gi
  tst/extreme/semieunit.tst
  tst/standard/attr.tst
  tst/standard/attrfp.tst
  tst/standard/dual.tst
  tst/standard/maximal.tst
  tst/standard/semidp.tst
  tst/standard/semieunit.tst
  tst/standard/semipperm.tst
  tst/workspaces/load-workspace.tst
  tst/workspaces/save-workspace.tst
Labels: minor
