Repository semigroups/Semigroups, pull requests merged in 2018-03, with the labels that each got.

#457 Smaller generating pair sets for RMS congruences
  doc/cong.xml
  gap/congruences/congrms.gi
  tst/standard/conguniv.tst
Labels: 3.0, improvement

#464 Resolve Issue #463: EvalString -> ValueGlobal
  gap/semigroups/semicons.gi
  gap/semigroups/semimaxplus.gi
  gap/tools/utils.gi
Labels: 3.0, improvement, minor

#465 Fix the hash function for McAlister triple semigroup elements
  gap/semigroups/semieunit.gi
Labels: 3.1, bug, critical

#467 attr: Add NambooripadPartialOrder & Leq methods
  doc/attr.xml
  gap/attributes/attr.gd
  gap/attributes/attr.gi
  tst/standard/attr.tst
Labels: 3.1, enhancement
