Repository semigroups/Semigroups, pull requests merged in 2019-06, with the labels that each got.

#603 bib: update very slightly
  doc/new_bibliography.xml
Labels: 3.*, minor

#600 Re-factor SmallestIdempotentPower
  gap/elements/elements.gi
  tst/standard/elements.tst
Labels: improvement

#605 Add IsSemigroupWithClosedIdempotents
  doc/properties.xml
  gap/attributes/properties.gd
  gap/attributes/properties.gi
  gap/ideals/ideals.gi
  gap/semigroups/semigraph.gi
  gap/semigroups/semirms.gi
Labels: new-feature, question

#606 Release candidate for v3.1.3
  CHANGELOG.md
  PackageInfo.g
  VERSION
  VERSIONS
Labels: release-candidate

#607 Fix issue 556
  gap/main/fropin.gi
  gap/main/orbits.gi
  gap/semigroups/grpperm.gi
  tst/standard/fropin.tst
  tst/standard/isorms.tst
  tst/standard/semibipart.tst
  tst/standard/semiboolmat.tst
  tst/standard/semipbr.tst
  tst/standard/semipperm.tst
  tst/standard/semirms.tst
  tst/standard/semitrans.tst
Labels: 3.*, bug-fix
