Repository semigroups/Semigroups, pull requests merged in 2020-05, with the labels that each got.

#665 Travis: build all branches except release candidates
  .travis.yml
Labels: travis

#666 Accommodate future changed ViewStrings in GAP, in isorms.tst
  tst/standard/isorms.tst
Labels: minor

#670 Release candidate for v3.3.1
  .VERSION
  CHANGELOG.md
  PackageInfo.g
  VERSIONS
Labels: release-candidate
