Repository semigroups/Semigroups, pull requests merged in 2021-05, with the labels that each got.

#768 Make compilation of manuals more robust
  PackageInfo.g
  ci/docker-install-deps.sh
  ci/docker-test.sh
  gap/doc.g
  gap/tools/utils.gd
  gap/tools/utils.gi
  makedoc.g
Labels: bug-fix, ci, documentation

#769 Update the `.release` script
  .release
Labels: minor

#776 Force cpplint-1.5.4 (not 1.5.5) in the CI
  .github/workflows/lint.yml
Labels: ci

#759 Allow ElementOfFpSemigroup to take simpler args
  doc/semifp.xml
  doc/z-chap10.xml
  gap/semigroups/semifp.gd
  gap/semigroups/semifp.gi
  tst/standard/semifp.tst
Labels: new-feature

#786 Run `SemigroupsTestInstall` and `TestManualExamples` in the GitHub Actions CI
  .github/workflows/ci.yml
  tst/teststandard.g
Labels: ci
