Repository semigroups/Semigroups, pull requests merged in 2023-03, with the labels that each got.

#911 Release candidate for v5.2.1
  .VERSION
  .mailmap
  CHANGELOG.md
  PackageInfo.g
  README.md
  VERSIONS
Labels: release-candidate

#902 Convert buildsystem to use Makefile.gappkg instead of automake
  .gitignore
  Makefile.am
  Makefile.gappkg
  Makefile.in
  configure.ac
  gapbind14/.gitignore
  gapbind14/CPPLINT.cfg
  gapbind14/demo/.gitignore
  m4/ax_check_hpcombi.m4
  m4/ax_check_libsemigroup.m4
  src/CPPLINT.cfg
Labels: build-system

#884 Some updates to improve the performance of `LatticeOfCongruences` and friends
  .gitignore
  Makefile.in
  doc/cong.xml
  doc/conglatt.xml
  doc/congsemigraph.xml
  doc/conguniv.xml
  doc/z-chap13.xml
  gap/congruences/cong.gd
  gap/congruences/cong.gi
  gap/congruences/conglatt.gd
  gap/congruences/conglatt.gi
  gap/congruences/congpairs.gi
  gap/congruences/congsemigraph.gd
  gap/congruences/congsemigraph.gi
  gapbind14/include/gapbind14/to_cpp.hpp
  src/conglatt.cpp
  src/conglatt.hpp
  src/pkg.cpp
  tst/standard/attributes/homomorph.tst
  tst/standard/congruences/cong.tst
  tst/standard/congruences/conglatt.tst
  tst/standard/congruences/congsemigraph.tst
  tst/standard/libsemigroups/sims1.tst
  tst/standard/semigroups/semiquo.tst
Labels: performance, refactor
