Repository semigroups/Semigroups, pull requests merged in 2024-11, with the labels that each got.

#1021 Better inverses
  doc/attr.xml
  doc/greens-generic.xml
  doc/z-chap11.xml
  gap/attributes/attr.gd
  gap/attributes/attr.gi
  gap/greens/froidure-pin.gi
  gap/semigroups/grpperm.gi
  tst/standard/attributes/attr.tst
  tst/standard/ideals/ideals.tst
  tst/standard/semigroups/grpperm.tst
  tst/standard/semigroups/semirms.tst
Labels: performance, enhancement

#1045 Use GAP kernel helper IS_STRING_REP to test for strings
  gapbind14/include/gapbind14/to_cpp.hpp
  src/to_cpp.hpp
Labels: gap-compatibility, C++ language

#1026 Better Nambooripad
  gap/attributes/attr.gi
  tst/standard/attributes/attr.tst
Labels: performance
